// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { AvailableAlbumsAlbumsGetData, AvailableAlbumsAlbumsGetResponses, CreateAlbumAlbumsPostData, CreateAlbumAlbumsPostResponses, CreateAlbumAlbumsPostErrors, GetAlbumInfoData, GetAlbumInfoResponses, GetAlbumInfoErrors, CaptureImageToAlbumData, CaptureImageToAlbumResponses, CaptureImageToAlbumErrors, LastImageForAlbumAlbumsAlbumNameLastImageGetData, LastImageForAlbumAlbumsAlbumNameLastImageGetResponses, LastImageForAlbumAlbumsAlbumNameLastImageGetErrors, GetQrCodesQrCodesGetData, GetQrCodesQrCodesGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Available Albums
 * An endpoint for listing albums and create new albums.
 *
 * On GET: Return list of all available albums.
 *
 * On POST: Create a new album with the given album name if it
 * does not already exists. If a description is given, set the
 * description of the album.
 */
export const availableAlbumsAlbumsGet = <ThrowOnError extends boolean = false>(options?: Options<AvailableAlbumsAlbumsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AvailableAlbumsAlbumsGetResponses, unknown, ThrowOnError>({
        url: '/albums/',
        ...options
    });
};

/**
 * Create Album
 */
export const createAlbumAlbumsPost = <ThrowOnError extends boolean = false>(options: Options<CreateAlbumAlbumsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateAlbumAlbumsPostResponses, CreateAlbumAlbumsPostErrors, ThrowOnError>({
        url: '/albums/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Album Info
 * An endpoint for listing images in an album or capture a new image
 * to the album
 *
 * On GET: Returns a list of the image links for all images in
 * <album_name>.
 *
 * On POST: Try to capture an image with the camera module and
 * add the image to <album_name>.
 *
 * If the album does not exist, an error message is returned.
 */
export const getAlbumInfo = <ThrowOnError extends boolean = false>(options: Options<GetAlbumInfoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAlbumInfoResponses, GetAlbumInfoErrors, ThrowOnError>({
        url: '/albums/{album_name}',
        ...options
    });
};

/**
 * Capture Album Image
 */
export const captureImageToAlbum = <ThrowOnError extends boolean = false>(options: Options<CaptureImageToAlbumData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CaptureImageToAlbumResponses, CaptureImageToAlbumErrors, ThrowOnError>({
        url: '/albums/{album_name}',
        ...options
    });
};

/**
 * Last Image For Album
 * Returns the url of the last image captured to the specified
 * album
 */
export const lastImageForAlbumAlbumsAlbumNameLastImageGet = <ThrowOnError extends boolean = false>(options: Options<LastImageForAlbumAlbumsAlbumNameLastImageGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<LastImageForAlbumAlbumsAlbumNameLastImageGetResponses, LastImageForAlbumAlbumsAlbumNameLastImageGetErrors, ThrowOnError>({
        url: '/albums/{album_name}/last_image',
        ...options
    });
};

/**
 * Get Qr Codes
 */
export const getQrCodesQrCodesGet = <ThrowOnError extends boolean = false>(options?: Options<GetQrCodesQrCodesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetQrCodesQrCodesGetResponses, unknown, ThrowOnError>({
        url: '/qr_codes/',
        ...options
    });
};