// This file is auto-generated by @hey-api/openapi-ts

/**
 * AlbumCaptureResponse
 */
export type AlbumCaptureResponse = {
    /**
     * Success
     */
    success: string;
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Thumbnail Url
     */
    thumbnail_url: string;
};

/**
 * AlbumCreateRequest
 */
export type AlbumCreateRequest = {
    /**
     * Album Name
     */
    album_name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * AlbumCreatedResponse
 */
export type AlbumCreatedResponse = {
    /**
     * Album Name
     */
    album_name: string;
    /**
     * Album Url
     */
    album_url: string;
};

/**
 * AlbumInfoResponse
 */
export type AlbumInfoResponse = {
    /**
     * Album Name
     */
    album_name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Image Urls
     */
    image_urls: Array<string>;
    /**
     * Thumbnail Urls
     */
    thumbnail_urls: Array<string>;
};

/**
 * AvailableAlbumsResponse
 */
export type AvailableAlbumsResponse = {
    /**
     * Available Albums
     */
    available_albums: Array<string>;
    /**
     * Forced Album
     */
    forced_album?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LastImageResponse
 */
export type LastImageResponse = {
    /**
     * Last Image Url
     */
    last_image_url: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AvailableAlbumsAlbumsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/albums/';
};

export type AvailableAlbumsAlbumsGetResponses = {
    /**
     * Successful Response
     */
    200: AvailableAlbumsResponse;
};

export type AvailableAlbumsAlbumsGetResponse = AvailableAlbumsAlbumsGetResponses[keyof AvailableAlbumsAlbumsGetResponses];

export type CreateAlbumAlbumsPostData = {
    body: AlbumCreateRequest;
    path?: never;
    query?: never;
    url: '/albums/';
};

export type CreateAlbumAlbumsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAlbumAlbumsPostError = CreateAlbumAlbumsPostErrors[keyof CreateAlbumAlbumsPostErrors];

export type CreateAlbumAlbumsPostResponses = {
    /**
     * Successful Response
     */
    200: AlbumCreatedResponse;
};

export type CreateAlbumAlbumsPostResponse = CreateAlbumAlbumsPostResponses[keyof CreateAlbumAlbumsPostResponses];

export type GetAlbumInfoData = {
    body?: never;
    path: {
        /**
         * Album Name
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}';
};

export type GetAlbumInfoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlbumInfoError = GetAlbumInfoErrors[keyof GetAlbumInfoErrors];

export type GetAlbumInfoResponses = {
    /**
     * Successful Response
     */
    200: AlbumInfoResponse;
};

export type GetAlbumInfoResponse = GetAlbumInfoResponses[keyof GetAlbumInfoResponses];

export type CaptureImageToAlbumData = {
    body?: never;
    path: {
        /**
         * Album Name
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}';
};

export type CaptureImageToAlbumErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CaptureImageToAlbumError = CaptureImageToAlbumErrors[keyof CaptureImageToAlbumErrors];

export type CaptureImageToAlbumResponses = {
    /**
     * Successful Response
     */
    200: AlbumCaptureResponse;
};

export type CaptureImageToAlbumResponse = CaptureImageToAlbumResponses[keyof CaptureImageToAlbumResponses];

export type LastImageForAlbumAlbumsAlbumNameLastImageGetData = {
    body?: never;
    path: {
        /**
         * Album Name
         */
        album_name: string;
    };
    query?: never;
    url: '/albums/{album_name}/last_image';
};

export type LastImageForAlbumAlbumsAlbumNameLastImageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LastImageForAlbumAlbumsAlbumNameLastImageGetError = LastImageForAlbumAlbumsAlbumNameLastImageGetErrors[keyof LastImageForAlbumAlbumsAlbumNameLastImageGetErrors];

export type LastImageForAlbumAlbumsAlbumNameLastImageGetResponses = {
    /**
     * Successful Response
     */
    200: LastImageResponse;
};

export type LastImageForAlbumAlbumsAlbumNameLastImageGetResponse = LastImageForAlbumAlbumsAlbumNameLastImageGetResponses[keyof LastImageForAlbumAlbumsAlbumNameLastImageGetResponses];

export type GetQrCodesQrCodesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/qr_codes/';
};

export type GetQrCodesQrCodesGetResponses = {
    /**
     * Response Get Qr Codes Qr Codes  Get
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};